/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIDemo */

#ifndef _Included_JNIDemo
#define _Included_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     JNIDemo
	 * Method:    sayHello
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_jni_JNIDemo_sayHello(JNIEnv*, jobject);
	JNIEXPORT int JNICALL Java_jni_JNIDemo_getSum(JNIEnv*, jobject, jint a, jint b);
	JNIEXPORT jobject JNICALL Java_jni_JNIDemo_getReverseString(JNIEnv*, jobject, jstring);
	JNIEXPORT void JNICALL Java_jni_JNIDemo_modifyClassMembers(JNIEnv*, jobject);
	JNIEXPORT void JNICALL Java_jni_JNIDemo_modifyStaticClassMembers(JNIEnv*, jobject);
	JNIEXPORT void JNICALL Java_jni_JNIDemo_nativeMethod(JNIEnv*, jobject);
#ifdef __cplusplus
}
#endif
#endif#pragma once
